name: Deploy to Azure using OIDC

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v3

    - name: 🧰 Setup .NET 9
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: 🔧 Restore and Build
      run: |
        dotnet restore
        dotnet build --configuration Release

    - name: Where are we on disk?
      run: | 
        ls -la
        find . -name "*.csproj"

    - name: 🚀 Run generator
      run: dotnet run

    - name: 📦 Prepare static output
      run: |
        mkdir publish
        cp index.html publish

    - name: 🔐 Login to Azure via OIDC
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: ☁️ Deploy static content to App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_APP_NAME }}
        package: publish
