name: Build and Deploy Aspire PR Summary

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v3

    - name: 🧰 Setup .NET 9
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: 🔧 Restore dependencies
      run: dotnet restore

    - name: 🏗️ Build the app
      run: dotnet build --configuration Release

    - name: 🚀 Run the console app
      run: dotnet run --configuration Release

    - name: 📦 Zip output (index.html, template.html, etc.)
      run: |
        mkdir publish
        cp index.html publish/
        cp template.html publish/ || true
        cp Aspire-PR-Summary.md publish/ || true
        zip -r publish.zip publish

    - name: ☁️ Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: publish.zip
